### ISSUE TITLE
Topic list

### ISSUE THREAD

**Issue by lcopi** [JohnStarich/cognitive-bias#1]
I'm very surprised to see "NASCAR is the greatest sport of all time" is not an accepted phrase. Please update this

**Comment by armadabootstrap** [comment]
But how do they feel about cheese? 🧀

**Comment by DerekMRoberts** [comment]
How am I supposed to preach the good word of our lord god Guy Fieri?

**Comment by JohnStarich** [comment]
Fixed in #2
